# Generated by Django 5.1.6 on 2025-02-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '指纹分类',
                'verbose_name_plural': '指纹分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指纹名称')),
                ('rule', models.CharField(max_length=255, verbose_name='匹配规则')),
                ('position', models.CharField(choices=[('header', 'HTTP头部'), ('body', '响应体'), ('url', 'URL'), ('all', '全部')], default='body', max_length=20, verbose_name='匹配位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='指纹描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='manager.fingerprintcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '指纹',
                'verbose_name_plural': '指纹',
                'ordering': ['category', 'name'],
            },
        ),
    ]
