# Generated by Django 5.1.6 on 2025-02-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_fingerprintcategory_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='主域名')),
                ('subdomain', models.CharField(max_length=255, verbose_name='子域名')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP地址')),
                ('status', models.IntegerField(blank=True, default=200, null=True, verbose_name='状态码')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='网站标题')),
                ('server', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
                'ordering': ['domain', 'subdomain'],
                'unique_together': {('domain', 'subdomain')},
            },
        ),
    ]
