# Generated by Django 5.1.6 on 2025-02-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'POC分类',
                'verbose_name_plural': 'POC分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='POC名称')),
                ('template', models.TextField(verbose_name='Nuclei模板')),
                ('severity', models.CharField(choices=[('info', '信息'), ('low', '低危'), ('medium', '中危'), ('high', '高危'), ('critical', '严重')], default='medium', max_length=20, verbose_name='危害等级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='POC描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='manager.poccategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': 'POC',
                'verbose_name_plural': 'POC',
                'ordering': ['category', 'name'],
            },
        ),
    ]
