# Generated by Django 5.1.6 on 2025-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_poccategory_poc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfoQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='域名')),
                ('has_cdn', models.BooleanField(default=False, verbose_name='是否有CDN')),
                ('ip_list', models.TextField(blank=True, null=True, verbose_name='IP列表')),
                ('whois_info', models.TextField(blank=True, null=True, verbose_name='WHOIS信息')),
                ('icp_info', models.TextField(blank=True, null=True, verbose_name='备案信息')),
                ('query_time', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
            options={
                'verbose_name': '基础信息查询',
                'verbose_name_plural': '基础信息查询',
                'ordering': ['-query_time'],
            },
        ),
    ]
