# Generated by Django 5.1.6 on 2025-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_baseinfoquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255, verbose_name='扫描目标')),
                ('scan_type', models.CharField(default='connect', max_length=50, verbose_name='扫描类型')),
                ('ports', models.TextField(blank=True, null=True, verbose_name='端口范围')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '失败')], max_length=20, verbose_name='扫描状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='扫描结果')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '端口扫描',
                'verbose_name_plural': '端口扫描',
                'ordering': ['-start_time'],
            },
        ),
    ]
