# Generated by Django 5.1.6 on 2025-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_portscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255, verbose_name='扫描目标')),
                ('wordlist', models.CharField(default='common', max_length=100, verbose_name='字典类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '失败')], max_length=20, verbose_name='扫描状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='扫描结果')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('extensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件扩展名')),
                ('threads', models.IntegerField(default=10, verbose_name='线程数')),
                ('timeout', models.IntegerField(default=10, verbose_name='超时时间(秒)')),
                ('status_codes', models.CharField(blank=True, max_length=100, null=True, verbose_name='状态码')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': '目录扫描',
                'verbose_name_plural': '目录扫描',
                'ordering': ['-start_time'],
            },
        ),
    ]
