# Generated by Django 5.2 on 2025-05-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0013_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="portscan",
            name="error_msg",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
    ]
