# Generated by Django 5.2 on 2025-05-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_portscan_error_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portscan",
            name="error_msg",
        ),
    ]
